name: quarto_website
channels:
  - conda-forge
dependencies:
  # core R runtime
  - r-base=4.3

  # tidy data + read_csv + pipes, etc.
  - r-tidyverse

  # project-root helper you’re using
  - r-here

  # needed for Quarto/R rendering
  - r-rmarkdown
  - r-knitr
